### ISSUE TITLE
Serverless スタックの CloudWatch Logs の保持期限を設定する

### ISSUE THREAD

**Issue by kamataryo** [geolonia/ops#9]
コスト圧縮のため将来設定する。`RetentionInDays` を設定。

```yaml
resources:
  Resources:
    getFooBarLogGroup:
      Properties:
        RetentionInDays: "90"
```
